[package]
name = "fullwidth_converter"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
unicode_hfwidth = "0.2.0"
unidecode = "0.3.0"